#!/bin/bash
# This script builds the Rusty Kaspa WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/sparkle-wasm32-sdk/web
mkdir -p release/sparkle-wasm32-sdk/nodejs
mkdir -p release/sparkle-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name sparkle-rpc --out-dir web/sparkle-rpc --features wasm32-sdk $@
# popd

# wasm-pack build --weak-refs --target web --out-name sparkle --out-dir web/sparkle-keygen --features wasm32-keygen $@
# wasm-pack build --weak-refs --dev --target web --out-name sparkle --out-dir web/sparkle-keygen-dev --features wasm32-keygen $@

# wasm-pack build --weak-refs --target web --out-name sparkle --out-dir web/sparkle-rpc --features wasm32-rpc $@
# wasm-pack build --weak-refs --dev --target web --out-name sparkle --out-dir web/sparkle-rpc-dev --features wasm32-rpc $@

# wasm-pack build --weak-refs --target web --out-name sparkle --out-dir web/sparkle-core --features wasm32-core $@
# wasm-pack build --weak-refs --dev --target web --out-name sparkle --out-dir web/sparkle-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name sparkle --out-dir web/sparkle --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name sparkle --out-dir web/sparkle-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name sparkle --out-dir nodejs/sparkle --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name sparkle --out-dir nodejs/sparkle-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name sparkle --out-dir build/docs/sparkle --features wasm32-sdk $@
# typedoc --name "Kaspa WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/sparkle-keygen ./build/docs/sparkle-keygen.ts
# typedoc --name "Kaspa WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/sparkle-rpc ./build/docs/sparkle-rpc.ts
# typedoc --name "Kaspa WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/sparkle-core ./build/docs/sparkle-core.ts
typedoc --name "Sparkle WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/sparkle ./build/docs/sparkle.ts

# cp -r ../rpc/wrpc/wasm/web/sparkle-rpc release/sparkle-wasm32-sdk/web/sparkle-rpc
# cp -r web/sparkle-keygen release/sparkle-wasm32-sdk/web/sparkle-keygen
# cp -r web/sparkle-keygen-dev release/sparkle-wasm32-sdk/web/sparkle-keygen-dev

# cp -r web/sparkle-rpc release/sparkle-wasm32-sdk/web/sparkle-rpc
# cp -r web/sparkle-rpc-dev release/sparkle-wasm32-sdk/web/sparkle-rpc-dev

# cp -r web/sparkle-core release/sparkle-wasm32-sdk/web/sparkle-core
# cp -r web/sparkle-core-dev release/sparkle-wasm32-sdk/web/sparkle-core-dev

cp -r web/sparkle release/sparkle-wasm32-sdk/web/sparkle
cp -r web/sparkle-dev release/sparkle-wasm32-sdk/web/sparkle-dev

cp -r nodejs/sparkle release/sparkle-wasm32-sdk/nodejs/sparkle
cp -r nodejs/sparkle-dev release/sparkle-wasm32-sdk/nodejs/sparkle-dev

# cp -r docs/sparkle-keygen release/sparkle-wasm32-sdk/docs/sparkle-keygen
# cp -r docs/sparkle-rpc release/sparkle-wasm32-sdk/docs/sparkle-rpc
# cp -r docs/sparkle-core release/sparkle-wasm32-sdk/docs/sparkle-core
cp -r docs/sparkle release/sparkle-wasm32-sdk/docs/sparkle

# pushd .
# cd release/sparkle-wasm32-sdk/examples
# npm install
# popd

# tsc release/sparkle-wasm32-sdk/examples/nodejs/typescript/

# cp index.html release/sparkle-wasm32-sdk/index.html
cp README.md release/sparkle-wasm32-sdk/README.md
# cp CHANGELOG.md release/sparkle-wasm32-sdk/CHANGELOG.md
cp LICENSE release/sparkle-wasm32-sdk/LICENSE

pushd .
cd release
zip -q -r sparkle-wasm32-sdk.zip sparkle-wasm32-sdk
popd
